### ISSUE TITLE
add Newsroom H1 block (again)

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_base#106]

**Comment by markconroy** [comment]
I'm stumped on this one. 

For some reason the template being picked up was the one from localgov_base instead of localgov_micrsites_base. When I cleared the cache it picked up the right template then and is working now. But I presume I've cleared the cache lots over the past week, so no idea why it started magically working. 

Can you test it by creating a newsroom. THEN clearing the cache and see if you have the title in position. You should also see breadcrumbs as well.

**Comment by msayoung** [comment]
yep, I'm seeing it without the cache clear. 
Closing
