### ISSUE TITLE
Breadcrumb region doesn't pick up page_background on taxonomy term pages

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_base#197]
![image](https://user-images.githubusercontent.com/3852805/206465307-e7f26a32-6c25-46ff-8d1c-13b80aa85ba5.png)

Set the page background colour to something not white. 
Add a taxonomy term
View the taxonomy term page

**Comment by markconroy** [comment]
This is tricky, and I'm not sure we can actually fix it.

We have 2 variables
- --page-background-colour: white
- --breadcrumbs-background-colour: white

When we set a background colour for our microsite, that changes --page-background-colour to red/yellow/whatever and applies to the whole <body> element. However, since we have explictly told --breadcrumbs-background-colour to be 'white', it remains so.

We could write something that says "if there is a value for --page-background-colour then force this to be the breadcrumb background colour too" but this might not be desired behaviour.

I'm open to suggestions on this one.

**Comment by markconroy** [comment]
And of course, just as I hit "send" above, I came up with a solution. 

> We could write something that says "if there is a value for --page-background-colour then force this to be the breadcrumb background colour too" but this might not be desired behaviour.

This is actually the solution I have gone for. I was thinking we could just add one line of CSS to set the breadcrumb colour per theme, but the point of microsites is that you don't need to create a theme per site, so it's probably a better behaviour for us to explictly set the breadcrumb background colour. 

It can then be overridden on a per theme basis by setting `!important` such as `--breadcrumb-background-colour: red !important;`
